/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.13).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Doctor;
import io.swagger.model.Doctors;
import io.swagger.model.Doctors2;

import java.io.IOException;
import java.util.List;
import java.util.Optional;

import io.swagger.annotations.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import com.fasterxml.jackson.databind.ObjectMapper;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-04-19T11:38:27.027Z")

@Api(value = "doctor", description = "the doctor API")
@RequestMapping(value = "/v1")
public interface DoctorApi {
	
	Logger log = LoggerFactory.getLogger(DoctorApi.class);
	
	default Optional<ObjectMapper> getObjectMapper(){
		return Optional.empty();
	}
	
	default Optional<HttpServletRequest> getRequest() {
		return Optional.empty();
	}
	
	default Optional<String> getAcceptHeader() {
		return getRequest().map(r -> r.getHeader("Accept"));
	}

    @ApiOperation(value = "Create doctor", nickname = "addDoctor", notes = "", tags={ "Doctor", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation") })
    @RequestMapping(value = "/Doctor",
        produces = { "application/xml", "application/json" }, 
        method = RequestMethod.POST)
    default ResponseEntity<Doctor> addDocotr(@ApiParam(value = "Created doctor object" ,required=true )  @Valid @RequestBody Doctor body) {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default DoctorApi interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.UNAUTHORIZED);
    }


    @ApiOperation(value = "Creates list of Doctor with given input array", nickname = "createDoctorWithArrayInput", notes = "", tags={ "Doctor", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation") })
    @RequestMapping(value = "/Doctor/createWithArray",
        produces = { "application/xml", "application/json" }, 
        method = RequestMethod.POST)
    default ResponseEntity<Void> createDoctorWithArrayInput(@ApiParam(value = "List of Doctor object" ,required=true )  @Valid @RequestBody List<Doctor> body) {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default DoctorApi interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }


    @ApiOperation(value = "delete doctor by id", nickname = "deleteDoctorById", notes = "This can only be done by the logged in doctor.", tags={ "Doctor", })
    @ApiResponses(value = { 
        @ApiResponse(code = 400, message = "Invalid Doctorname supplied"),
        @ApiResponse(code = 404, message = "Doctor not found") })
    @RequestMapping(value = "/doctor/{id}",
        produces = { "application/xml", "application/json" }, 
        method = RequestMethod.DELETE)
    default ResponseEntity<Doctor> deletedoctor(@ApiParam(value = "The name that needs to be deleted",required=true) @PathVariable("doctorname") String doctorname) {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default DoctorApi interface so no example is generated");
        }
        return new ResponseEntity<Doctor>(HttpStatus.NOT_IMPLEMENTED);
    }


    @ApiOperation(value = "Get doctor by doctor name", nickname = "getdoctorByName", notes = "", response = Doctor.class, tags={ "Doctor", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = Doctor.class),
        @ApiResponse(code = 404, message = "doctor not found") })
    @RequestMapping(value = "/Doctor/{Doctorname}",
        produces = { "application/xml", "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<Doctor> getdoctorByName(@ApiParam(value = "The name that needs to be fetched. Use doctor 1 for testing. ",required=true) @PathVariable("Doctorname") String Doctorname) {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
            if (getAcceptHeader().get().contains("application/xml")) {
                try {
                    return new ResponseEntity<>(getObjectMapper().get().readValue("<Doctor>  <id>123</id>  <Doctorname>aeiou</Doctorname>  <firstName>aeiou</firstName>  <lastName>aeiou</lastName>  <email>aeiou</email>  <password>aeiou</password>  <phone>aeiou</phone>  <avatarUrl>aeiou</avatarUrl>  <Doctorvotes>123</Doctorvotes></Doctor>", Doctor.class), HttpStatus.NOT_IMPLEMENTED);
                } catch (IOException e) {
                    log.error("Couldn't serialize response for content type application/xml", e);
                    return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
                }
            }
            if (getAcceptHeader().get().contains("application/json")) {
                try {
                    return new ResponseEntity<>(getObjectMapper().get().readValue("{  \"firstName\" : \"firstName\",  \"lastName\" : \"lastName\",  \"password\" : \"password\",  \"phone\" : \"phone\",  \"avatarUrl\" : \"avatarUrl\",  \"Doctorvotes\" : 6,  \"id\" : 0,  \"Doctorname\" : \"Doctorname\",  \"email\" : \"email\"}", Doctor.class), HttpStatus.NOT_IMPLEMENTED);
                } catch (IOException e) {
                    log.error("Couldn't serialize response for content type application/json", e);
                    return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
                }
            }
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default DoctorApi interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }


    @ApiOperation(value = "Logs doctor into the system", nickname = "logindoctor", notes = "", response = String.class, tags={ "Doctor", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = String.class),
        @ApiResponse(code = 400, message = "Invalid Doctorname/password supplied") })
    @RequestMapping(value = "/Doctor/login",
        produces = { "application/xml", "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<String> logindoctor(@NotNull @ApiParam(value = "The doctor name for login", required = true) @Valid @RequestParam(value = "doctorname", required = true) String doctorname,@NotNull @ApiParam(value = "The password for login in clear text", required = true) @Valid @RequestParam(value = "password", required = true) String password) {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
            if (getAcceptHeader().get().contains("application/xml")) {
                try {
                    return new ResponseEntity<>(getObjectMapper().get().readValue("aeiou", String.class), HttpStatus.NOT_IMPLEMENTED);
                } catch (IOException e) {
                    log.error("Couldn't serialize response for content type application/xml", e);
                    return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
                }
            }
            if (getAcceptHeader().get().contains("application/json")) {
                try {
                    return new ResponseEntity<>(getObjectMapper().get().readValue("\"\"", String.class), HttpStatus.NOT_IMPLEMENTED);
                } catch (IOException e) {
                    log.error("Couldn't serialize response for content type application/json", e);
                    return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
                }
            }
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default DoctorApi interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }


    @ApiOperation(value = "Logs out current logged in Doctor session", nickname = "logoutDoctor", notes = "", tags={ "Doctor", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation") })
    @RequestMapping(value = "/Doctor/logout",
        produces = { "application/xml", "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<List<Doctor>> logoutDoctor() {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default DoctorApi interface so no example is generated");
        }
        return new ResponseEntity<List<Doctor>> (HttpStatus.NOT_IMPLEMENTED);
    }


    @ApiOperation(value = "Updated information about doctor", nickname = "updateDoctor", notes = "This can only be done by the logged in doctor.", tags={ "Doctor", })
    @ApiResponses(value = { 
        @ApiResponse(code = 400, message = "Invalid Doctor supplied"),
        @ApiResponse(code = 404, message = "Doctor not found") })
    @RequestMapping(value = "/Doctor",
        produces = { "application/xml", "application/json" }, 
        method = RequestMethod.PUT)
    default ResponseEntity<List<Doctor>> updateDoctor(@ApiParam(value = "name that need to be updated",required=true) @PathVariable("Doctorname") String Doctorname,@ApiParam(value = "Updated Doctor object" ,required=true )  @Valid @RequestBody Doctor body) {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default DoctorApi interface so no example is generated");
        }
        return new ResponseEntity<List<Doctor>>(HttpStatus.NOT_IMPLEMENTED);
    }

}
