/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.13).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Body;
import io.swagger.model.Message;
import io.swagger.model.Messages;
import io.swagger.model.Messages2;
import io.swagger.annotations.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import com.fasterxml.jackson.databind.ObjectMapper;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import javax.validation.constraints.*;

import java.io.IOException;
import java.util.List;
import java.util.Optional;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-04-19T11:38:27.027Z")

@Api(value = "message", description = "the message API")
@RequestMapping(value = "/v1")
public interface MessageApi {

	Logger log = LoggerFactory.getLogger(MessageApi.class);
	
	default Optional<ObjectMapper> getObjectMapper(){
		return Optional.empty();
	}
	
	default Optional<HttpServletRequest> getRequest() {
		return Optional.empty();
	}
	
	default Optional<String> getAcceptHeader() {
		return getRequest().map(r -> r.getHeader("Accept"));
	}
	
    @ApiOperation(value = "Get all user message", nickname = "getMessage", notes = "Retrieves all message ", response = Message.class, responseContainer = "List", authorizations = {
        @Authorization(value = "messagetore_auth", scopes = {
            @AuthorizationScope(scope = "write:messages", description = "modify messages in your account"),
            @AuthorizationScope(scope = "read:messages", description = "read your messages")
            })
    }, tags={ "message", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK - message have been returned", response = Message.class, responseContainer = "List"),
        @ApiResponse(code = 400, message = "BadRequest - Not all input parameters were provided or provided input parameters do not satisfy validation rules.") })
    @RequestMapping(value = "/message",
        method = RequestMethod.GET)
    default ResponseEntity<List<Message>> getMessage() {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
            if (getAcceptHeader().get().contains("application/json")) {
                try {
                    return new ResponseEntity<>(getObjectMapper().get().readValue("[ {  \"receiverusersId\" : 1,  \"senderusersId\" : 6,  \"id\" : 0,  \"content\" : \"content\"}, {  \"receiverusersId\" : 1,  \"senderusersId\" : 6,  \"id\" : 0,  \"content\" : \"content\"} ]", List.class), HttpStatus.NOT_IMPLEMENTED);
                } catch (IOException e) {
                    log.error("Couldn't serialize response for content type application/json", e);
                    return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
                }
            }
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default messageApi interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }


    @ApiOperation(value = "Send a message", nickname = "sendmessage", notes = "Send a message to an user.", authorizations = {
        @Authorization(value = "messagetore_auth", scopes = {
            @AuthorizationScope(scope = "write:message", description = "modify message in your account")
            })
    }, tags={ "message", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "Created - Message has been created"),
        @ApiResponse(code = 500, message = "InternalServerError - The server encountered an unexpected error and was unable to complete your request.") })
    @RequestMapping(value = "/message",
        method = RequestMethod.POST)
    default ResponseEntity<List<Message>> sendmessage(@ApiParam(value = "" ,required=true )  @Valid @RequestBody Body body) {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default messageApi interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }

}
